- project:
    name: openstack/aodh
    check:
      jobs:
        - aodh-dsvm-tempest-plugin-mysql
        - aodh-dsvm-tempest-plugin-postgresql
        - telemetry-dsvm-integration-aodh
    gate:
      jobs:
        - aodh-dsvm-tempest-plugin-mysql
        - aodh-dsvm-tempest-plugin-postgresql
        - telemetry-dsvm-integration-aodh

- job:
    name: aodh-dsvm-tempest-plugin-mysql
    parent: legacy-dsvm-base
    run: playbooks/legacy/aodh-dsvm-tempest-plugin-mysql/run
    post-run: playbooks/legacy/aodh-dsvm-tempest-plugin-mysql/post
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/aodh
      - openstack/tempest

- job:
    name: aodh-dsvm-tempest-plugin-postgresql
    parent: legacy-dsvm-base
    run: playbooks/legacy/aodh-dsvm-tempest-plugin-postgresql/run
    post-run: playbooks/legacy/aodh-dsvm-tempest-plugin-postgresql/post
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/aodh
      - openstack/tempest

- job:
    name: telemetry-dsvm-integration-aodh
    parent: legacy-dsvm-base
    run: playbooks/legacy/telemetry-dsvm-integration-aodh/run
    post-run: playbooks/legacy/telemetry-dsvm-integration-aodh/post
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/aodh
      - openstack/ceilometer
      - openstack/panko
      # following are required when DEVSTACK_GATE_HEAT, which this
      # job turns on
      - openstack/dib-utils
      - openstack/diskimage-builder
